$ErrorActionPreference = "Stop"

$StartupFolder = [System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::Startup)
$TargetVbs = Join-Path $StartupFolder "RunnerUp-AutoStart.vbs"
$SourceVbs = Join-Path $PSScriptRoot "start-runnerup-daemon.vbs"

# Create a VBScript in Startup folder that executes the daemon launcher
$vbsContent = @"
' Auto-generated by Runner Up installer
Set objShell = CreateObject("WScript.Shell")
objShell.Run """wscript.exe"" """ & "$SourceVbs" & """", 0, False
"@

Set-Content -Path $TargetVbs -Value $vbsContent -Encoding ASCII

Write-Host "[SUCCESS] Auto-start entry installed at:" -ForegroundColor Green
Write-Host "  $TargetVbs" -ForegroundColor Cyan
Write-Host ""
Write-Host "Runner Up backend and Cloudflare tunnel will now start automatically whenever your PC turns on or you log in!" -ForegroundColor Green
